# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  # NOTE: env must be set; see README
  PROFILE: "{{ .nixos_profile }}"
  USER: "dan"
  FLAKE: "./nixos_flake"
  # NOTE: --impure is used to load env var in flake.nix
  OPTIONS: "--impure"

tasks:
  default:
    cmds:
      - task --list-all --order alphanumeric
    silent: true

  check:
    cmds:
      - |
        if [[ -z "{{ .PROFILE }}" ]]; then
          echo "Error: set and source .envrc before running. See README."
          exit 1
        fi
    silent: true

  # TODO: add prepare command to copy /etc/nixos/hardware-config.nix to $FLAKE/
  copy-hardwareconfig:
    cmds:
      - echo "noop"
    desc: "Generate and copy a hardware-configuration.nix into the flake dir"

  rebuild:nixos:
    cmds:
      - task: check
      - nh os switch {{ .FLAKE }} -- {{ .OPTIONS }}
    env:
      FLAKE: "{{ .USER_WORKING_DIR }}/nixos_flake/profiles/{{ .PROFILE }}"
    desc: "Use nix-helper to rebuild the nixos system configuration and switch to it"

  rebuild:hm:
    cmds:
      - task: check
      - nh home switch -c {{ .USER }} {{ .FLAKE }} -- {{ .OPTIONS }}
    env:
      FLAKE: "{{ .USER_WORKING_DIR }}/nixos_flake/profiles/{{ .PROFILE }}"
    desc: "Use nix-helper to rebuild the home-manager user configuration and switch to it"

  rebuild:
    desc: "Rebuild and switch to the latest nixos and home-manager configs"
    cmds:
      - task: check
      - task: rebuild:nixos
      - task: rebuild:hm

  install:nixos:
    cmds:
      - task: check
      - sudo nixos-rebuild switch --flake {{ .FLAKE }} {{ .OPTIONS }}
    desc: "Rebuild the nixos system configuration and switch to it"

  install:hm:
    cmds:
      - task: check
      - home-manager switch --flake {{ .FLAKE }}#{{ .USER }} {{ .OPTIONS }}
    desc: "Rebuild the home-manager configuration and switch to it"

  install:
    desc: "Build and switch to the latest nixos and home-manager configs"
    cmds:
      - task: install:nixos
      - task: install:hm
