# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  PROFILE: "wsl"
  USER: "dan"
  FLAKE: "./nixos_flake"

tasks:
  default:
    cmds:
      - task --list-all --order alphanumeric
    silent: true

  rebuild:nixos:
    cmds:
      - nh os switch {{ .FLAKE }}
    env:
      FLAKE: "{{ .USER_WORKING_DIR }}/nixos_flake/profiles/{{ .PROFILE }}"
    desc: "Use nix-helper to rebuild the nixos system configuration and switch to it"

  rebuild:hm:
    cmds:
      - nh home switch -c {{ .USER }} {{ .FLAKE }}
    env:
      FLAKE: "{{ .USER_WORKING_DIR }}/nixos_flake/profiles/{{ .PROFILE }}"
    desc: "Use nix-helper to rebuild the home-manager user configuration and switch to it"

  rebuild:
    desc: "Rebuild and switch to the latest nixos and home-manager configs"
    cmds:
      - task: rebuild:nixos
      - task: rebuild:hm

  install:nixos:
    cmds:
      - sudo nixos-rebuild switch --flake {{ .FLAKE }}
    desc: "Rebuild the nixos system configuration and switch to it"

  install:hm:
    cmds:
      - home-manager switch --flake {{ .FLAKE }}#{{ .USER }}
    desc: "Rebuild the home-manager configuration and switch to it"

  install:
    desc: "Build and switch to the latest nixos and home-manager configs"
    cmds:
      - task: install:nixos
      - task: install:hm

# TODO: add prepare command to copy /etc/nixos/hardware-config.nix to $FLAKE/
